# Generated by Django 5.0.6 on 2024-08-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('plans', '0003_alter_operation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
    ]
