# Generated by Django 5.0.6 on 2024-08-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_operation_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='name',
        ),
    ]
